#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bumper,         sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor5,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motor7,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motor8,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motor9,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motor10,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//port 1,5,10 broken
task main()
{
	while(true)
	{
		//	motor[motor1]= motor[motor2] = motor[motor3] = motor[motor4] =motor[motor5] = motor[motor6]= motor[motor7]=motor[motor8] =motor[motor9] =motor[motor10] = 127
		if(SensorValue[bumper] == 1)
		{
			motor[motor5] =127;
			SensorValue[encoder] = 0;
			wait1Msec(1000);
			int rpm = abs(SensorValue[encoder]*60/360);
			writeDebugStream("\n %d %1.2f%c",rpm,nImmediateBatteryLevel/1000.0,'V');
			//writeDebugStream("\n %d",rpm);
		}
		else
			motor[motor5] = 0;
	}
}







//resetTimer(T1);
//resetEncoder();
//while(encoder < targetDistance)
//{
//	if(time1[T1] > 2000)
//	{
//		resetEncoder();
//		drivemotor = 0;
//	}
//	else{
//		drivemotor = 127;
//	}
//}
