#pragma config(Sensor, dgtl1,  PClaw,          sensorDigitalOut)
#pragma config(Motor,  port1,           LeftBackDrive, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightBackDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightBackDrive2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightFrontDrive2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftBackDrive2, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//global variable
//Drive Variables
int driveDirectionF = 0;
int driveDirectionT = 0;
int driveDirectionH = 0;

int RFrontDrive	= 0;
int RBackDrive	= 0;
int LFrontDrive	= 0;
int LBackDrive	= 0;

int ArmPower = 0;
int last_Btn5U_Value = 0;

const unsigned int TrueSpeed[128] =
{
	0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	0, 0, 0, 0, 0, 22, 22, 23, 24, 24,       //0, 21, 21, 21, 22, 22, 22, 23, 24, 24,
	25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
	28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
	37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
	41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
	46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
	52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
	71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
	80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
	88, 89, 89, 90, 90,127,127,127
};


int motorCap(int motorPowervalue)
{

	if (motorPowervalue >= 127)
	{
		return (127);
	}
	else if (motorPowervalue <= -127)
	{
		return (-127);
	}
	return (motorPowervalue);
}


task main()
{
	while(true){
		//Motor Controller
		motor[RightFrontDrive] = motor[RightFrontDrive2] = RFrontDrive;
		motor[RightBackDrive] = motor[RightBackDrive2]= RBackDrive;
		motor[LeftFrontDrive] = LFrontDrive;
		motor[LeftBackDrive] = motor[LeftBackDrive2] = LBackDrive;
		motor[LeftArm] = motor[RightArm] = ArmPower;


		//~~~~~~~~~~~~~~~~~~ Drive direction for Truespeed ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

		if(vexRT[Ch3] > 10)
		{
			driveDirectionF = 1;
		}
		else if (vexRT[Ch3] < 10)
		{
			driveDirectionF = -1;
		}
		if(vexRT[Ch4] > 10)
		{
			driveDirectionH = 1;
		}
		else if (vexRT[Ch4] < 10)
		{
			driveDirectionH = -1;
		}
		if (vexRT[Ch1]>10)
		{
			driveDirectionT = 1;
		}
		else if (vexRT[Ch1]<10)
		{
			driveDirectionT = -1;
		}
		//~~~~~~~~~Drive Controls~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

		RFrontDrive = motorCap(-(TrueSpeed[abs(vexRT[Ch1])]*driveDirectionT)+(TrueSpeed[abs(vexRT[Ch3])]*driveDirectionF)
		- (TrueSpeed[abs(vexRT[Ch4])]*driveDirectionH));
		RBackDrive = motorCap(-(TrueSpeed[abs(vexRT[Ch1])]*driveDirectionT)+(TrueSpeed[abs(vexRT[Ch3])]*driveDirectionF)
		+ (TrueSpeed[abs(vexRT[Ch4])]*driveDirectionH));
		LFrontDrive = motorCap((TrueSpeed[abs(vexRT[Ch1])]*driveDirectionT)+(TrueSpeed[abs(vexRT[Ch3])]*driveDirectionF)
		+ (TrueSpeed[abs(vexRT[Ch4])]*driveDirectionH));
		LBackDrive = motorCap((TrueSpeed[abs(vexRT[Ch1])]*driveDirectionT)+(TrueSpeed[abs(vexRT[Ch3])]*driveDirectionF)
		- (TrueSpeed[abs(vexRT[Ch4])]*driveDirectionH));

		//~~~~~~~~~~~~ ARM CONTROL~~~~~~~~~~

		if(vexRT[Btn5U])
			ArmPower = 127;
		else if (vexRT[Btn5D])
			ArmPower = -60;
		else
			ArmPower = 0;


		//~~~~~~~~~~~~~~~~~~~~~~CLAW FOR MOTORS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		if(vexRT[Btn6U])
			motor[Claw] = 127;
		else if(vexRT[Btn6D])
			motor[Claw] = -127;
		else if(vexRT[Btn8U])
			motor[Claw] = 15;
		else
			motor[Claw] = 0;

		//~~~~~~~~~~~~~~~~~~~~~~~~~CLAW~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		int curr_Btn5U_Value = vexRT[Btn8D];
		if (vexRT[Btn8D] ==1 && curr_Btn5U_Value != last_Btn5U_Value && SensorValue[PClaw] ==0)
		{
			SensorValue[PClaw] = 1;
		}
		else if (vexRT[Btn8D] ==1 && curr_Btn5U_Value != last_Btn5U_Value && SensorValue[PClaw] == 1)
		{
			SensorValue[PClaw] = 0;
		}
		last_Btn5U_Value = curr_Btn5U_Value;
	}
}
